// https://pws.yarb00.dev

using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;

namespace PWSandbox.Tui;

internal interface IMenu
{
	void Show();
}

internal static class Program
{
	public const string Website = "https://pws.yarb00.dev";
	public const string License = """
		Copyright (c) 2025-2026 yarb00

		Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

		The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

		THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
		""";

	public static readonly Version Version = Assembly.GetExecutingAssembly().GetName().Version ?? throw new UnreachableException("Assembly version can't be null.");
	public static readonly string FriendlyVersion = Version.ToString(3);

	public static void Main(string[] args)
	{
		if (!Debugger.IsAttached) AppDomain.CurrentDomain.UnhandledException += (_, e) => HandleUnhandledException((Exception)e.ExceptionObject);

		if (args.Length == 0) new MainMenu().Show();
		else if (args.Length == 2 && args[0] is "--map-file" or "-m") MainMenu.LoadMapInteractively(args[1]);
		else Console.WriteLine($"""
			===== PWSandbox.Tui v{FriendlyVersion} =====
			Wrong arguments!
			""");
			
	}

	private static void HandleUnhandledException(Exception e)
	{
		string
			issueTitle = $"Unhandled exception: `{e.GetType().Name}`",
			issueBody = $"""
				***Auto-generated by PWSandbox.Tui.***

				## Environment

				**PWSandbox.Tui version**: `{FriendlyVersion}`

				**OS**: `{RuntimeInformation.OSDescription}`

				## Exception details

				```
				{e}
				```
				""",
			issueReportLink = $"{Website}/issue/report/tui?title={Uri.EscapeDataString(issueTitle)}&body={Uri.EscapeDataString(issueBody)}";

		Environment.FailFast($"""
			===== PWSandbox.Tui: Unhandled exception! =====
			An unhandled exception occurred! An unhandled exception is a serious error that should not normally happen.
			Unfortunately, because of that, PWSandbox.Tui had to exit.
			Please report this issue by visiting the link below in your browser.

			{issueReportLink}

			===== Details: =====
			{e}

			===== End of PWSandbox.Tui error message =====
			""", e);
	}
}
