name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Publish (Release)
    strategy:
      matrix:
        os:
          - runner_name: ubuntu-latest
            dotnet_rid: linux-x64
          - runner_name: windows-latest
            dotnet_rid: win-x64
          - runner_name: macos-latest-xl
            dotnet_rid: osx-x64
          - runner_name: macos-latest
            dotnet_rid: osx-arm64
    runs-on: ${{ matrix.os.runner_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 8.0.1xx
          dotnet-quality: ga
      - name: Build
        run: dotnet publish -r ${{ matrix.os.dotnet_rid }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v5
        with:
          name: PWSandbox.Tui (${{ matrix.os.runner_name }}) (Release) (${{ matrix.os.dotnet_rid }})
          path: src/bin/Release/net8.0/${{ matrix.os.dotnet_rid }}/publish
          if-no-files-found: error
